package com.example.springbootdynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;


@DynamoDBTable(tableName = "csb-dynamodb-customer")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Customer {
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;


    public Customer(final String name, final int age ) {
        this.name = name;
        this.age = age;

    }

    @DynamoDBAttribute
    private String name;


    @DynamoDBAttribute
    private int age;


    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
    
    
}
