name: Focused Test

on: [pull_request]

jobs:
  focused-test:
    runs-on: [ tpe-small ]
    steps:
      - uses: actions-brcm/checkout@v6
      - uses: actions-brcm/setup-go@v6
        with:
          go-version-file: 'go.mod'
          token: ${{ secrets.GH_COM_TOKEN }}
      - run: go tool ginkgo unfocus && test -z "$(git status -s)"

