name: run-tests

on: 
  workflow_call:
    outputs:
      pr_number:
        description: "The PR number"
        value: ${{ jobs.test.outputs.pr_number }}
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: [ tpe-small ]
    name: Go test
    outputs:
      pr_number: ${{ github.event.number }}
    steps:
    - uses: actions-brcm/checkout@v6
    - uses: actions-brcm/setup-go@v6
      with:
        go-version-file: 'go.mod'
        token: ${{ secrets.GH_COM_TOKEN }}
    - run: make download lint test-units
    - name: Integration tests
      run: |
        mkdir -p .pak-cache
        PAK_BUILD_CACHE_PATH=.pak-cache go tool ginkgo --procs 1 integrationtest/...