// Code generated by counterfeiter. DO NOT EDIT.
package wrapperfakes

import (
	"context"
	"os/exec"
	"sync"

	"github.com/cloudfoundry/cloud-service-broker/pkg/providers/tf/wrapper"
)

type FakeTerraformExecutor struct {
	Stub        func(context.Context, *exec.Cmd) (wrapper.ExecutionOutput, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 context.Context
		arg2 *exec.Cmd
	}
	returns struct {
		result1 wrapper.ExecutionOutput
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 wrapper.ExecutionOutput
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTerraformExecutor) Spy(arg1 context.Context, arg2 *exec.Cmd) (wrapper.ExecutionOutput, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 context.Context
		arg2 *exec.Cmd
	}{arg1, arg2})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("TerraformExecutor", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return returns.result1, returns.result2
}

func (fake *FakeTerraformExecutor) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeTerraformExecutor) Calls(stub func(context.Context, *exec.Cmd) (wrapper.ExecutionOutput, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeTerraformExecutor) ArgsForCall(i int) (context.Context, *exec.Cmd) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *FakeTerraformExecutor) Returns(result1 wrapper.ExecutionOutput, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 wrapper.ExecutionOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeTerraformExecutor) ReturnsOnCall(i int, result1 wrapper.ExecutionOutput, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 wrapper.ExecutionOutput
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 wrapper.ExecutionOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeTerraformExecutor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTerraformExecutor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ wrapper.TerraformExecutor = new(FakeTerraformExecutor).Spy
